# Generated by Django 6.0.3 on 2026-03-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0002_tenant_contract_end_date_tenant_contract_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('dashboard', 'Dashboard'), ('users', 'User Management'), ('campus', 'Campus Management'), ('academics', 'Academics'), ('timetable', 'Timetabling'), ('exams', 'Exam Management'), ('resources', 'Asset & Resource Management'), ('bookings', 'Facility Bookings'), ('reports', 'Analytics & Reports'), ('notifications', 'Notifications'), ('settings', 'Settings')], max_length=100)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['module_name', 'action'],
                'unique_together': {('module_name', 'action')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['role', 'permission__module_name', 'permission__action'],
                'unique_together': {('role', 'permission', 'tenant')},
            },
        ),
    ]
