# Generated by Django 6.0.3 on 2026-03-12 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_rolepermission'),
        ('tenants', '0002_tenant_contract_end_date_tenant_contract_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(blank=True, help_text='e.g. +91, +1', max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_rules', to='accounts.permission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user_permissions', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'permission__module_name', 'permission__action'],
                'unique_together': {('user', 'permission', 'tenant')},
            },
        ),
    ]
