# Generated by Django 6.0.3 on 2026-03-16 11:33
# Modified: clear old campus CharField data before converting to ForeignKey

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_country_code_userpermission'),
        ('campus', '0001_initial'),
    ]

    operations = [
        # Step 1: Wipe any existing campus string values so type change doesn't fail
        migrations.RunSQL(
            sql="UPDATE accounts_customuser SET campus = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: Change the field from CharField to ForeignKey
        migrations.AlterField(
            model_name='customuser',
            name='campus',
            field=models.ForeignKey(
                blank=True,
                help_text='Assigned campus — required for campus-scoped IT admins',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='campus.campus',
            ),
        ),
    ]
