# Generated by Django 6.0.3 on 2026-03-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_campus_field_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('academic_admin', 'Academic Admin'), ('facility_manager', 'Facility Manager'), ('it_admin', 'IT Admin'), ('hod', 'Head of Department'), ('faculty', 'Faculty'), ('student', 'Student'), ('research_scholar', 'Research Scholar'), ('external_user', 'External User')], max_length=50, unique=True),
        ),
    ]
