# Generated by Django 6.0.3 on 2026-03-09 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('resources', '0001_initial'),
        ('tenants', '0002_tenant_contract_end_date_tenant_contract_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger', models.CharField(choices=[('role_student', 'User Role: Student'), ('role_external', 'User Role: External User'), ('role_research', 'User Role: Research Scholar'), ('resource_auditorium', 'Resource Type: Auditorium'), ('resource_seminar_hall', 'Resource Type: Seminar Hall'), ('resource_lab', 'Resource Type: Lab/Lab Instrument'), ('resource_restricted', 'Resource: Requires Approval'), ('time_weekend', 'Time: Weekend'), ('time_after_hours', 'Time: After Hours (after 6 PM or before 8 AM)'), ('duration_long', 'Duration: Over 4 Hours'), ('role_facility_manager', 'User Role: Facility Manager (Direct Book)'), ('all', 'All Bookings')], max_length=50)),
                ('action', models.CharField(choices=[('auto_approve', 'Auto Approve'), ('require_approval', 'Require Approval'), ('block', 'Block Completely')], default='require_approval', max_length=20)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Lower = evaluated first')),
                ('approver_roles', models.JSONField(default=list, help_text='List of role names that can approve. Empty = any admin.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies', to='tenants.tenant')),
            ],
            options={
                'ordering': ['priority', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('room', 'Room / Facility'), ('sub_unit', 'Sub-Resource Unit (Seat/System)'), ('sports_turf', 'Sports Turf'), ('seminar_hall', 'Seminar Hall'), ('auditorium', 'Auditorium'), ('lab_instrument', 'Lab Instrument'), ('meeting_room', 'Meeting Room')], max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('expected_attendees', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('active', 'Active'), ('completed', 'Completed'), ('conflict', 'Conflict')], default='draft', max_length=20)),
                ('requires_approval', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.bookingpolicyrule')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_requested', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='resources.resource')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='campus.room')),
                ('sub_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='resources.subresourceunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingConflictLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_conflicts', to='tenants.tenant')),
                ('conflicting_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_existing', to='bookings.bookingrequest')),
                ('new_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_new', to='bookings.bookingrequest')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(help_text='Stored file URL (S3, Cloudinary, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_attachments', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bookings.bookingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='BookingApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info', 'More Info Requested')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_approvals', to='tenants.tenant')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='bookings.bookingrequest')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('repeat_until', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='bookings.bookingrequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bookings', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BookingParticipantInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role_label', models.CharField(blank=True, help_text="e.g. 'Presenter', 'Guest', 'Student'", max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_participants', to='tenants.tenant')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bookings.bookingrequest')),
            ],
            options={
                'unique_together': {('booking', 'email')},
            },
        ),
    ]
