# Generated by Django 6.0.3 on 2026-03-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(help_text='Unique identifier like mod_core', max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('price_annual', models.DecimalField(decimal_places=2, help_text='Yearly price in INR', max_digits=10)),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price in INR', max_digits=10, null=True)),
                ('is_annual_only', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list, help_text='List of feature strings')),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
