# Generated by Django 6.0.3 on 2026-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_pricingmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('tenant_created', 'Tenant Created'), ('tenant_updated', 'Tenant Updated'), ('tenant_suspended', 'Tenant Suspended'), ('tenant_activated', 'Tenant Activated'), ('tenant_archived', 'Tenant Archived'), ('tenant_deleted', 'Tenant Deleted'), ('subscription_updated', 'Subscription Updated')], max_length=50),
        ),
    ]
