# Generated by Django 6.0.3 on 2026-03-09 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('tenants', '0002_tenant_contract_end_date_tenant_contract_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head_of_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_departments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('visiting', 'Visiting Faculty'), ('adjunct', 'Adjunct Faculty'), ('hod', 'Head of Department'), ('dean', 'Dean'), ('other', 'Other')], default='assistant_professor', max_length=30)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('max_weekly_hours', models.PositiveSmallIntegerField(default=18, help_text='Max teaching hours per week')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('retired', 'Retired'), ('resigned', 'Resigned')], default='active', max_length=20)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='academics.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profiles', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__full_name'],
                'unique_together': {('tenant', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. B.E. Computer Science, M.Sc. Physics', max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('degree_type', models.CharField(choices=[('ug', 'Under Graduate (UG)'), ('pg', 'Post Graduate (PG)'), ('diploma', 'Diploma'), ('phd', 'Ph.D / Research'), ('integrated', 'Integrated (5-year)'), ('certificate', 'Certificate'), ('other', 'Other')], default='ug', max_length=20)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('total_semesters', models.PositiveSmallIntegerField(default=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. 2022-2026', max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tenants.tenant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.program')),
            ],
            options={
                'ordering': ['-start_year'],
                'unique_together': {('tenant', 'program', 'start_year')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. A, B, C', max_length=50)),
                ('strength', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.batch')),
                ('class_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_sections', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tenants.tenant')),
            ],
            options={
                'ordering': ['batch', 'name'],
                'unique_together': {('batch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Semester 1, Sem-III', max_length=100)),
                ('semester_number', models.PositiveSmallIntegerField(help_text='Numeric order within program')),
                ('term', models.CharField(choices=[('odd', 'Odd Semester'), ('even', 'Even Semester'), ('summer', 'Summer Term'), ('trimester_1', 'Trimester 1'), ('trimester_2', 'Trimester 2'), ('trimester_3', 'Trimester 3')], default='odd', max_length=20)),
                ('academic_year', models.CharField(help_text='e.g. 2024-25', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='tenants.tenant')),
            ],
            options={
                'ordering': ['program', 'semester_number'],
                'unique_together': {('tenant', 'program', 'semester_number', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=30)),
                ('course_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical / Lab'), ('tutorial', 'Tutorial'), ('project', 'Project'), ('elective', 'Elective'), ('audit', 'Audit / Non-Credit'), ('online', 'Online / MOOC'), ('seminar', 'Seminar')], default='theory', max_length=20)),
                ('credits', models.DecimalField(decimal_places=1, default=3.0, max_digits=4)),
                ('lecture_hours', models.PositiveSmallIntegerField(default=3)),
                ('tutorial_hours', models.PositiveSmallIntegerField(default=1)),
                ('practical_hours', models.PositiveSmallIntegerField(default=0)),
                ('is_elective', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tenants.tenant')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.semester')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Lab Group 1', max_length=100)),
                ('strength', models.PositiveSmallIntegerField(default=30)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academics.section')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentRoomPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_type', models.CharField(blank=True, help_text='Leave blank = applies to all', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_preferences', to='academics.department')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_preferences', to='campus.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_room_preferences', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('department', 'room', 'course_type')},
            },
        ),
        migrations.CreateModel(
            name='FacultyPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_days', models.JSONField(default=list, help_text="e.g. ['mon', 'wed', 'fri']")),
                ('preferred_time_start', models.TimeField(blank=True, null=True)),
                ('preferred_time_end', models.TimeField(blank=True, null=True)),
                ('avoid_early_morning', models.BooleanField(default=False)),
                ('avoid_consecutive_hours', models.BooleanField(default=False)),
                ('max_courses_per_semester', models.PositiveSmallIntegerField(default=4)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_courses', models.ManyToManyField(blank=True, related_name='preferred_by', to='academics.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_preferences', to='tenants.tenant')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='academics.facultyprofile')),
            ],
            options={
                'unique_together': {('tenant', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=5)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_availabilities', to='tenants.tenant')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='academics.facultyprofile')),
            ],
            options={
                'ordering': ['faculty', 'day', 'start_time'],
                'unique_together': {('faculty', 'day', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='tenants.tenant')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_course_sections', to='academics.facultyprofile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='academics.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='academics.semester')),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sections', to='academics.studentgroup')),
            ],
            options={
                'ordering': ['course__code'],
                'unique_together': {('course', 'section', 'semester')},
            },
        ),
    ]
