# Generated by Django 6.0.3 on 2026-03-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='campus.campus'),
        ),
    ]
