# Generated by Django 6.0.3 on 2026-03-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_department_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional biography / profile summary'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='industry_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='research_interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated or freeform list of skills'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
