# Generated by Django 6.0.3 on 2026-03-26 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_program_syllabus_upload_fields'),
        ('tenants', '0002_tenant_contract_end_date_tenant_contract_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_domains', to='academics.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_domains', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'department', 'name')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='primary_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_courses', to='academics.subjectdomain'),
        ),
        migrations.AddField(
            model_name='course',
            name='secondary_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_courses', to='academics.subjectdomain'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='primary_specialization_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_specialization_faculty', to='academics.subjectdomain'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='secondary_specialization_domains',
            field=models.ManyToManyField(blank=True, related_name='secondary_specialization_faculty', to='academics.subjectdomain'),
        ),
        migrations.CreateModel(
            name='FacultyEligibleSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('auto_suggested', 'Auto Suggested'), ('hod_added', 'HOD Added')], default='auto_suggested', max_length=20)),
                ('status', models.CharField(choices=[('auto_suggested', 'Auto Suggested'), ('hod_approved', 'HOD Approved'), ('hod_rejected', 'HOD Rejected'), ('hod_added', 'HOD Added')], default='auto_suggested', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_faculty', to='academics.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_subjects', to='academics.facultyprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_eligible_subjects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['faculty__user__full_name', 'course__code'],
                'unique_together': {('tenant', 'faculty', 'course')},
            },
        ),
        migrations.CreateModel(
            name='FacultyPreferredSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_rankings', to='academics.course')),
                ('faculty_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_subjects', to='academics.facultypreference')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_preferred_subjects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['faculty_preference', 'rank'],
                'unique_together': {('faculty_preference', 'course'), ('faculty_preference', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='FacultySubjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subject_assignments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_faculty_assignments', to='academics.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_subject_assignments', to='academics.facultyprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_subject_assignments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['faculty__user__full_name', 'course__code'],
                'unique_together': {('tenant', 'faculty', 'course')},
            },
        ),
    ]
