# Generated by Django 6.0.3 on 2026-03-11 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_leaverequest_substitutionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='substitutionrequest',
            name='hod_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='substitutionrequest',
            name='hod_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substitutionrequest',
            name='hod_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_reviewed_substitutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='substitutionrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitution_requests_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='substitutionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending HOD Review'), ('hod_approved', 'HOD Approved'), ('hod_rejected', 'HOD Rejected'), ('approved', 'Fully Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
