# Generated by Django 6.0.3 on 2026-03-12 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_department_campus'),
        ('campus', '0001_initial'),
        ('timetable', '0003_hod_substitution_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableplan',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_plans', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='timetableplan',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_plans', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='timetableplan',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_plans', to='academics.program'),
        ),
    ]
