# Generated by Django 6.0.3 on 2026-03-09 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenant_contract_end_date_tenant_contract_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Campuses',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Short code (e.g., BLD-A)', max_length=50)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='tenants.tenant')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='campus.campus')),
            ],
            options={
                'ordering': ['campus__name', 'name'],
                'unique_together': {('tenant', 'campus', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FacilityTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_tags', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_number', models.IntegerField(help_text='0 for Ground, negative for basements')),
                ('name', models.CharField(blank=True, help_text="Optional human readable name, e.g. 'Mezzanine'", max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='campus.building')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='tenants.tenant')),
            ],
            options={
                'ordering': ['building__name', 'floor_number'],
                'unique_together': {('tenant', 'building', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_code', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('seminar_hall', 'Seminar Hall'), ('auditorium', 'Auditorium'), ('meeting_room', 'Meeting Room'), ('conference_room', 'Conference Room'), ('library_space', 'Library Space'), ('sports_facility', 'Sports Facility'), ('research_lab', 'Research Lab'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'type_code')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=50)),
                ('room_name', models.CharField(blank=True, help_text="Optional special name, e.g. 'Newton Lab'", max_length=255)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('is_wheelchair_accessible', models.BooleanField(default=False)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_video_conferencing', models.BooleanField(default=False)),
                ('has_smart_board', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, help_text='Owning/Primary department', max_length=255, null=True)),
                ('under_maintenance', models.BooleanField(default=False)),
                ('available_facilities', models.ManyToManyField(blank=True, related_name='rooms', to='campus.facilitytag')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='campus.building')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='campus.campus')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='campus.floor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tenants.tenant')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='campus.roomtype')),
            ],
            options={
                'ordering': ['building__name', 'floor__floor_number', 'room_number'],
                'unique_together': {('tenant', 'building', 'room_number')},
            },
        ),
    ]
