# Generated by Django 6.0.3 on 2026-03-09 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('tenants', '0002_tenant_contract_end_date_tenant_contract_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_code', models.CharField(help_text='Unique code e.g. LAB-01-SYS-001', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_total', models.PositiveIntegerField(default=1)),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('unit_type', models.CharField(choices=[('unit', 'Unit'), ('set', 'Set'), ('seat', 'Seat'), ('system', 'Computer System'), ('instrument', 'Instrument'), ('kit', 'Kit'), ('pair', 'Pair')], default='unit', max_length=20)),
                ('bookable_as_whole', models.BooleanField(default=True, help_text='Can the entire resource be booked at once?')),
                ('bookable_per_unit', models.BooleanField(default=False, help_text='Can individual units/seats/systems be booked?')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('requires_approval', models.BooleanField(default=False, help_text='Bookings require admin approval?')),
                ('restricted_roles', models.JSONField(blank=True, default=list, help_text='List of role names that can book this resource')),
                ('under_maintenance', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='campus.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('calibration', 'Calibration'), ('inspection', 'Inspection')], default='preventive', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assigned_to', models.CharField(blank=True, help_text='Name or role responsible', max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='tenants.tenant')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='resources.resource')),
            ],
            options={
                'ordering': ['scheduled_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category_type', models.CharField(choices=[('equipment', 'Equipment'), ('lab_instrument', 'Lab Instrument'), ('sports', 'Sports Equipment'), ('research', 'Research Tool'), ('it_asset', 'IT Asset'), ('furniture', 'Furniture'), ('av_equipment', 'AV Equipment'), ('other', 'Other')], default='equipment', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name e.g. 'Monitor'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.resourcecategory'),
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_tags', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.resourcetag'),
        ),
        migrations.CreateModel(
            name='SubResourceUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_label', models.CharField(help_text="e.g. 'System-01', 'Seat 3A', 'Microscope-2'", max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='resources.resource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_resource_units', to='tenants.tenant')),
            ],
            options={
                'ordering': ['resource__name', 'unit_label'],
                'unique_together': {('resource', 'unit_label')},
            },
        ),
        migrations.CreateModel(
            name='UtilizationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booked_by', models.CharField(help_text='User email or ID', max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilization_logs', to='resources.resource')),
                ('sub_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilization_logs', to='resources.subresourceunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilization_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('tenant', 'resource_code')},
        ),
        migrations.CreateModel(
            name='RoomResourceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_mappings', to='resources.resource')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_resource_mappings', to='campus.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_resource_mappings', to='tenants.tenant')),
            ],
            options={
                'ordering': ['room__room_number', 'resource__name'],
                'unique_together': {('tenant', 'room', 'resource')},
            },
        ),
    ]
